[project]
name = "flaskr"
version = "1.0.0"
description = "The basic blo app build in the Flask tutorial."
dependencies = [
  "flask",
]

[build-system]
requires = ["flit_core<4"]
build-backend = "flit_core.buildapi"
